
services:
  fastapi:
    image: fastapi_pr
    environment:
      DATABASE_URL: postgresql://strider:8569@postgresql:5432/mydatabase
    depends_on:
      - postgresql
    ports:
      - "8080:8000"
    container_name: project
    restart: always
  
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_USER: strider
      POSTGRES_PASSWORD: 8569
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    container_name: postgresql
    restart: always

volumes:
  pgdata:
  logs:
